version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  backend:
    build: ./backend
    env_file: .env
    depends_on: [postgres, redis]
    ports: ["8000:8000"]

  ai_service:
    build: ./ai_service
    env_file: .env
    ports: ["8001:8001"]

  iot_service:
    build: ./iot_service
    env_file: .env
    depends_on: [redis]
    ports: ["8002:8002"]

volumes:
  pgdata:
